# Cloud Build configuration to trigger the deployment script
steps:
  - id: "Run deploy.sh"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - ./deploy.sh --hostId="${_HOST_ID}" --location="${_LOCATION}" --hostShortId="${_HOST_SHORT_ID}"

substitutions:
  _HOST_ID: "@default/my-first-host"
  _LOCATION: "europe-west1"
  _HOST_SHORT_ID: "1ac9d8"

timeout: 3600s
